### PR TITLE
Include example of Built Collections comparison

### LINKED ISSUE #277: Built Collections deep comparison question
The [documentation](https://github.com/google/built_collection.dart#built-collections-are-comparable) states:

> Built Collections do a deep comparison against other Built Collections of the same type, only.

I took that to mean that a `BuiltList` can be deep compared only if the collections it contains are also `BuiltList`s.

Here's an example of what I understood to be true:

```dart
// ✔ can be deep compared; BuiltList contains BuiltLists
BuiltList<BuiltList<String>> builtList1 = . . .
BuiltList<BuiltList<String>> builtList2 = . . .

----------

// ❌ can NOT be deep compared; BuiltList contains BuiltSets — not same types
BuiltList<BuiltSet<String>> builtList1 = . . .
BuiltList<BuiltSet<String>> builtList2 = . . .
```

However, I tested this, and it seems like my understanding is incorrect:
```dart
test(
  'Test BuiltList equality',
  () {
    BuiltList<BuiltSet<String>> list1 = BuiltList<BuiltSet<String>>([BuiltSet<String>(["One"])]);
    BuiltList<BuiltSet<String>> list2 = BuiltList<BuiltSet<String>>([BuiltSet<String>(["One"])]);
    expect(list1, equals(list2)); // true
  },
);
```

After testing this, and considering the possible interpretations of the above documentation, I believe I misunderstood the documentation, initially. I was hoping to confirm this and get clarification over what scenario the documentation above is describing. If I can get clarification, I'd be happy to make a PR to the README with a code sample to illustrate the above documentation to help others avoid experiencing the same misinterpretation I did.

### PR DESCRIPTION
**Pull request by kwilliams3**
resolves #277

### CODE REVIEW

**Comment by kwilliams3** [comment]
@davidmorgan, do you think I should go through the effort of expanding the ". . ." in the code example with an actual implementation showing the code for comparison? In the second half of the code example, I could copy/paste the implementation from the first half, but then comment that it gives a runtime/compilation error. (not sure yet which error it gives, I'll have to test it out personally to see)

**Comment by davidmorgan** [comment]
Thanks K! Some suggestions:

I think the nested collections may be distracting, how about instead using a custom type so that the example can talk about operator==?

e.g.

```
BuiltList<CustomType> list1;
BuiltList<CustomType> list2;
```

then say these are deep comparable, meaning they will be compared by calling the `operator==` implementation of `CustomType`. In particular, if it compares by value, they will be compared by value.

For the "doesn't compare" example, how about

```
BuiltSet<CustomType> set1;
```

then remark that it will never be equal to list1 or list2, even if the contents are identical, because it is a different collection type?

Thanks.

**Comment by kwilliams3** [comment]
@davidmorgan, what do you think about the changes I just introduced?

**Comment by kwilliams3** [comment]
@davidmorgan, I replaced the example with your example code. What do you think?

**Comment by davidmorgan** [comment]
Looks good, thanks!

**Pull request merged**
