### PR TITLE
Relax type checks based on strong mode guarantees.

### PR DESCRIPTION
**Pull request by davidmorgan**
Remove test cases that strong mode catches for us. Fix the remainder to be strong mode clean.

---
This change is [Reviewable](https://reviewable.io/reviews/google/built_collection.dart/75)

### CODE REVIEW

**Comment by manuelF** [comment]
:lgtm:

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/built_collection.dart/75#-:-KUqjpvzr6_FKICIeSfA:bnfp4nl)*

**Comment by manuelF** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/built_collection.dart/75)*

**Comment by ranquild** [comment]
*[a discussion](https://reviewable.io:443/reviews/google/built_collection.dart/75#-KUql1wZJMv9kmHKcE83:-KUql1wZJMv9kmHKcE84:bymidvk) (no related file):*
I think that `_checkElements` should call `_checkElement` as it was previously because methods already accept strongly-typed values, collections or functions that return `E`. also `_checkElements` should use `Iterable<E>` as parameter type.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/built_collection.dart/75)*

**Comment by davidmorgan** [comment]
*[a discussion](https://reviewable.io:443/reviews/google/built_collection.dart/75#-KUql1wZJMv9kmHKcE83:-KUqn78fHOq68PC0deE-:bra14sx) (no related file):*
<details><summary><i>Previously, ranquild wrote…</i></summary>
> I think that `_checkElements` should call `_checkElement` as it was previously because methods already accept strongly-typed values, collections or functions that return `E`. also `_checkElements` should use `Iterable<E>` as parameter type.
</details>
Yes, there are still runtime checks that could be removed.

We're in a grey area here: even with strong mode it's possible to create incorrectly typed collections, for example

new List<String>.from([1, 2, 3])

passes strong mode checks and creates a List<String> that contains int.

This PR relaxes checks on methods that take a single element; those seem relatively likely to be safe, even if you could still pass a bad value to them if you tried hard enough:

new List<String>.from([1, 2, 3])[0]

This seems unlikely enough in practice that I think it's okay to drop the runtime checks.

If we're convinced that wrong types in iterables doesn't happen in practice we could relax those checks too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/built_collection.dart/75)*

**Comment by ranquild** [comment]
*[a discussion](https://reviewable.io:443/reviews/google/built_collection.dart/75#-KUql1wZJMv9kmHKcE83:-KUqu7ow19ns3Bkp5bMX:b-voh6sp) (no related file):*
<details><summary><i>Previously, davidmorgan (David Morgan) wrote…</i></summary>
> Yes, there are still runtime checks that could be removed.
> 
> We're in a grey area here: even with strong mode it's possible to create incorrectly typed collections, for example
> 
> new List<String>.from([1, 2, 3])
> 
> passes strong mode checks and creates a List<String> that contains int.
> 
> This PR relaxes checks on methods that take a single element; those seem relatively likely to be safe, even if you could still pass a bad value to them if you tried hard enough:
> 
> new List<String>.from([1, 2, 3])[0]
> 
> This seems unlikely enough in practice that I think it's okay to drop the runtime checks.
> 
> If we're convinced that wrong types in iterables doesn't happen in practice we could relax those checks too.
</details>
You are correct, analyzer will not cache such issues at the moment, however checked mode in Dartium will. If it's okay I would like to remove runtime type check here too because performance penalty is too much and developers debug code in checked mode anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/built_collection.dart/75)*

**Comment by davidmorgan** [comment]
*[a discussion](https://reviewable.io:443/reviews/google/built_collection.dart/75#-KUql1wZJMv9kmHKcE83:-KUqvXzDk7FySIVN0e1I:byoc7ol) (no related file):*
<details><summary><i>Previously, ranquild wrote…</i></summary>
> You are correct, analyzer will not cache such issues at the moment, however checked mode in Dartium will. If it's okay I would like to remove runtime type check here too because performance penalty is too much and developers debug code in checked mode anyway.
</details>
By default built_collection should provide strong type guarantees.

But, it would be possible to relax these as an option. e.g. we could have a startup option

configure_built_collections(trustCollectionTypes: true)

-- what do you think?

I won't get to it this week unfortunately -- I'm going to the Dart Developer Summit :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/built_collection.dart/75)*

**Comment by ranquild** [comment]
*[a discussion](https://reviewable.io:443/reviews/google/built_collection.dart/75#-KUql1wZJMv9kmHKcE83:-KUqw98-nne9ju1EMjtQ:be65wrf) (no related file):*
<details><summary><i>Previously, davidmorgan (David Morgan) wrote…</i></summary>
> By default built_collection should provide strong type guarantees.
> 
> But, it would be possible to relax these as an option. e.g. we could have a startup option
> 
> configure_built_collections(trustCollectionTypes: true)
> 
> -- what do you think?
> 
> I won't get to it this week unfortunately -- I'm going to the Dart Developer Summit :)
</details>
I think it's fine for now if we have at least fast `add` methods with relaxed types checks. As for static option, I think it's better not to add it. Thanks! 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/built_collection.dart/75)*

**Comment by ranquild** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/google/built_collection.dart/75#-:-KUr3BvM42MyXydM2mM0:bnfp4nl)*

**Comment by davidmorgan** [comment]
*[a discussion](https://reviewable.io:443/reviews/google/built_collection.dart/75#-KUql1wZJMv9kmHKcE83:-KUr481inKHYw1NkGPg1:b-jhyyta) (no related file):*
<details><summary><i>Previously, ranquild wrote…</i></summary>
> I think it's fine for now if we have at least fast `add` methods with relaxed types checks. As for static option, I think it's better not to add it. Thanks! 
</details>
Got it. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/built_collection.dart/75)*

**Pull request merged**
